[build]
# 使用并行编译
jobs = 4

[target.x86_64-apple-darwin]
rustflags = [
  # 启用增量编译
  "-C", "incremental=/tmp/rust-incremental",
]

[target.aarch64-apple-darwin] 
rustflags = [
  # 启用增量编译
  "-C", "incremental=/tmp/rust-incremental",
]

# 网络配置
[net]
retry = 2
git-fetch-with-cli = true

# 缓存配置
[cargo-new]
vcs = "git"

# 注册表配置
[registries.crates-io]
protocol = "sparse"